name: ci

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build g++ \
            zlib1g-dev libtbb-dev \
            libnetcdf-dev libnetcdf-c++4-dev \
            libboost-all-dev

      - name: Configure
        run: cmake -S . -B build -G Ninja -DPK_USE_ZLIB=ON -DPK_USE_ZSTD=OFF

      - name: Build
        run: cmake --build build -j 2

